# todo-tui.conf
# Place this file at ~/.config/todo-tui/todo-tui.conf

# Set a persistent file path (instead of ./TODO_tui.md):
# file-path = ~/Documents/TODO_tui.md

# Or use commands to save/load the file remotely.
# $FILE is replaced with a temporary local file path.
# file-cmd-save = rclone copy $FILE gdrive:docs
# file-cmd-load = rclone copy gdrive:docs/TODO_tui.md $FILE
