# todo-tui.conf
# Place this file at ~/.config/todo-tui/todo-tui.conf

# File name can be changed like this:
# $FILE = MyCustomTodo

# Set a persistent file path (instead of ./TODO_tui.md):
# file-path = ~/Documents/

# Or use commands to save/load the file remotely.
# $PATH is a temporary local file path.
# file-cmd-save = rclone copy $PATH gdrive:docs/$FILE
# file-cmd-load = rclone copy gdrive:docs/$FILE $PATH
